// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-project-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/data.ts
var SITE_URL = "https://masterdrez.com";
var overview = {
  name: "Masterdrez",
  tagline: "Es m\xE1s que un ajedrez",
  description: "Masterdrez es una plataforma de ajedrez para cuatro jugadores: un emprendimiento de base tecnol\xF3gica de Buenos Aires, Argentina, que combina videojuego, juego de mesa, educaci\xF3n y eSports.",
  location: "Buenos Aires, Argentina",
  model: "Freemium: acceso gratuito con opciones premium",
  playUrl: `${SITE_URL}/game`,
  stats: [
    { value: "2M+", label: "Usuarios Potenciales" },
    { value: "4", label: "Jugadores Simult\xE1neos" },
    { value: "10min", label: "Recompensas Diarias" }
  ]
};
var features = [
  { title: "4 Jugadores Simult\xE1neos", text: "Partidas revolucionarias con hasta 4 jugadores en tiempo real, creando din\xE1micas \xFAnicas de estrategia y alianzas." },
  { title: "Partidas R\xE1pidas y Lentas", text: "Desde partidas r\xE1pidas de 15 minutos hasta torneos de un d\xEDa completo." },
  { title: "Recompensas Diarias", text: "Juega al menos 10 minutos diarios y recibe recompensas que mejoran tu experiencia y ranking." },
  { title: "Clanes y Torneos", text: "\xDAnete a clanes, participa en torneos \xE9picos y compite en campa\xF1as con narrativa envolvente." },
  { title: "IA Integrada", text: "Entrena con una IA avanzada, forma equipos mixtos o practica estrategias complejas." },
  { title: "Comunidad Global", text: "Conecta con jugadores de todo el mundo, especialmente en Latinoam\xE9rica." },
  { title: "Multiplataforma", text: "Disponible en m\xF3viles, tablets y PC, con progreso sincronizado." },
  { title: "Contenido Educativo", text: "Videos instructivos, libros digitales y material educativo." },
  { title: "Juego de Mesa (F\xEDsico)", text: "Versi\xF3n f\xEDsica de Masterdrez para disfrutar en casa con familia y amigos." }
];
var rules = [
  {
    topic: "estilos",
    title: "Estilos",
    count: 2,
    options: ["Dupla", "Unitario"],
    text: "Cada Estilo se debe anunciar al inicio de la partida y se realiza una vez comenzado el juego."
  },
  {
    topic: "empates",
    title: "Empates",
    count: 3,
    options: ["Mastertablas", "Tritablas", "Tablas"],
    text: "El empate puede ser de 4 (Mastertablas), 3 (Tritablas) o 2 (Tablas) jugadores."
  },
  {
    topic: "modos",
    title: "Modos",
    count: 5,
    options: ["Pr\xF3cer", "Paz", "Esclavo", "Genocidio", "De Facto"],
    text: "Cada Modo se debe anunciar al inicio de la partida y se realiza una vez dado el Mate al primer Rey."
  }
];

// src/lib/mcp/tools/get-project-overview.ts
var get_project_overview_default = defineTool({
  name: "get_project_overview",
  title: "Resumen del proyecto",
  description: "Devuelve el resumen p\xFAblico de Masterdrez: propuesta, ubicaci\xF3n, modelo de negocio, m\xE9tricas y URL para jugar.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
    structuredContent: overview
  })
});

// src/lib/mcp/tools/list-features.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";
var list_features_default = defineTool2({
  name: "list_features",
  title: "Listar caracter\xEDsticas",
  description: "Lista las caracter\xEDsticas p\xFAblicas de la plataforma Masterdrez, con filtro opcional por texto.",
  inputSchema: {
    query: z.string().optional().describe("Texto opcional para filtrar caracter\xEDsticas por t\xEDtulo o descripci\xF3n.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const items = q ? features.filter(
      (f) => f.title.toLowerCase().includes(q) || f.text.toLowerCase().includes(q)
    ) : features;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-game-rules.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.23.8";
var get_game_rules_default = defineTool3({
  name: "get_game_rules",
  title: "Reglas del juego",
  description: "Devuelve las reglas p\xFAblicas de Masterdrez (Estilos, Empates y Modos). Se puede pedir un tema espec\xEDfico.",
  inputSchema: {
    topic: z2.enum(["estilos", "empates", "modos"]).optional().describe("Tema de reglas a consultar. Si se omite, devuelve todos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => {
    const items = topic ? rules.filter((r) => r.topic === topic) : rules;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-play-link.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_play_link_default = defineTool4({
  name: "get_play_link",
  title: "Enlace para jugar",
  description: "Devuelve el enlace p\xFAblico para jugar al tablero de Masterdrez de cuatro jugadores en el navegador.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = { site: SITE_URL, play: overview.playUrl };
    return {
      content: [{ type: "text", text: `Juega en ${data.play}` }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "videojuego-masterdrez-2d",
  title: "Videojuego-Masterdrez-2D",
  version: "0.1.0",
  instructions: "Herramientas p\xFAblicas de Masterdrez, el ajedrez para cuatro jugadores. Usa `get_project_overview` para el resumen del proyecto, `list_features` para las caracter\xEDsticas de la plataforma, `get_game_rules` para Estilos, Empates y Modos, y `get_play_link` para el enlace de juego.",
  tools: [get_project_overview_default, list_features_default, get_game_rules_default, get_play_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
